DuaControl.Web/Controllers/FacturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DuaControl.Web.Data;
using DuaControl.Web.Data.Entities;
using DuaControl.Web.Data.Helpers;
using DuaControl.Web.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using DuaControl.Web.Security;

namespace DuaControl.Web.Controllers
{
    [Authorize]
    public class FacturasController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IHostingEnvironment _environment;
        private readonly IUserSession _userSession;

        public FacturasController(
            DataContext context,
            IConverterHelper converterHelper,
            ICombosHelper combosHelper,
            IHostingEnvironment environment,
            IUserSession userSession)
        {
            _context = context;
            _converterHelper = converterHelper;
            _combosHelper = combosHelper;
            _environment = environment;
            _userSession = userSession;
        }

        // GET: Facturas
        public IActionResult Index()
        {
            return View(_context.Facturas
                .Include(f => f.Adjuntos)
                .Include(f => f.Client)
                .Include(f => f.Port));
        }

        // GET: Facturas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factura = await _context.Facturas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (factura == null)
            {
                return NotFound();
            }

            return View(factura);
        }

        // GET: Facturas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var factura = await _context.Facturas.FindAsync(id);
            var factura = await _context.Facturas
                .Include(f => f.Client)
                .Include(f => f.Port)
                .Include(f => f.Adjuntos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (factura == null)
            {
                return NotFound();
            }
            return View(_converterHelper.ToFacturaViewModel(factura));
        }

        // POST: Facturas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(FacturaViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var factura = await _converterHelper.ToFacturaAsync(model);
                    _context.Update(factura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacturaExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return new JsonResult(true);
            }
            model.Puertos = _combosHelper.GetComboPorts();
            return View(model);
        }

        private bool FacturaExists(int id)
        {
            return _context.Facturas.Any(e => e.Id == id);
        }

        [HttpPost]
        public async Task<IActionResult> AddFileAsync(FacturaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var files = HttpContext.Request.Form.Files;
                    var path = Path.Combine(_environment.WebRootPath, @"uploads\" + model.InvoiceNumber);
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    if (files.Count > 0)
                    {
                        foreach (var file in files)
                        {
                            if (file.Length > 0)
                            {
                                if (System.IO.File.Exists(path + @"\" + file.FileName))
                                {
                                    var adjunto1 = await _context.Adjuntos.FirstOrDefaultAsync(a => a.DocumentName.Trim() == file.FileName.Trim());
                                    if (adjunto1 != null)
                                    {
                                        await DeleteFileAsync(adjunto1.Id);
                                    }
                                }
                                //var completePath = Path.Combine(@path, file.FileName);
                                using (var fileStream = new FileStream(Path.Combine(path, file.FileName), FileMode.Create))
                                {
                                    await file.CopyToAsync(fileStream);
                                }

                                var adjunto = new Adjunto
                                {
                                    RegisterDate = DateTime.Now,
                                    User = _userSession.UserName,
                                    DocumentUrl = path,
                                    DocumentName = file.FileName,
                                    Factura = await _context.Facturas.FirstOrDefaultAsync(f => f.Id == model.Id)
                                };
                                _context.Adjuntos.Add(adjunto);
                                await _context.SaveChangesAsync();
                            }
                        }
                    }
                    return new JsonResult(true);
                }
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction($"Edit/{model.Id}");
        }

        [Authorize(Policy =Constants.RoleNames.Administrator)]
        public async Task<IActionResult> DeleteFileAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adjunto = await _context.Adjuntos
                .Include(a => a.Factura)
                .FirstOrDefaultAsync(a => a.Id == id.Value);
            if (adjunto == null)
            {
                return NotFound();
            }

            if (System.IO.File.Exists(adjunto.DocumentUrl + @"\" + adjunto.DocumentName))
            {
                System.IO.File.Delete(adjunto.DocumentUrl + @"\" + adjunto.DocumentName);
            }

            _context.Adjuntos.Remove(adjunto);
            await _context.SaveChangesAsync();
            //return new JsonResult(true);
            return RedirectToAction($"{nameof(Edit)}/{adjunto.Factura.Id}");
        }
    }
}

DuaControl.Web/Controllers/PuertosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DuaControl.Web.Data;
using DuaControl.Web.Data.Entities;
using Microsoft.AspNetCore.Authorization;

namespace DuaControl.Web.Controllers
{
    [Authorize]
    public class PuertosController : Controller
    {
        private readonly DataContext _context;

        public PuertosController(DataContext context)
        {
            _context = context;
        }

        // GET: Puertos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Puertos.ToListAsync());
        }

        // GET: Puertos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var puerto = await _context.Puertos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (puerto == null)
            {
                return NotFound();
            }

            return View(puerto);
        }

        // GET: Puertos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Puertos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Puerto puerto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(puerto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(puerto);
        }

        // GET: Puertos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var puerto = await _context.Puertos.FindAsync(id);
            if (puerto == null)
            {
                return NotFound();
            }
            return View(puerto);
        }

        // POST: Puertos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Puerto puerto)
        {
            if (id != puerto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(puerto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PuertoExists(puerto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(puerto);
        }

        // GET: Puertos/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var puerto = await _context.Puertos
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (puerto == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(puerto);
        //}

        // POST: Puertos/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var puerto = await _context.Puertos.FindAsync(id);
        //    _context.Puertos.Remove(puerto);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool PuertoExists(int id)
        {
            return _context.Puertos.Any(e => e.Id == id);
        }

        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> VerifyPort(string Name)
        {
            return Json(await _context.Puertos.FirstOrDefaultAsync(p => p.Name == Name) == null ? (object)true : $"El puerto {Name} ya existe.");
        }
    }
}

DuaControl.Web/Views/Shared/AccessDenied.cshtml
@using DuaControl.Web.Data
@{
    ViewData["Title"] = Constants.MainPages.AccessDenied;
}

<section class="content-header clearfix">
    <h1><i class="fa fa-exclamation-triangle text-danger" aria-hidden="true"></i> @ViewData["Title"]</h1>
</section>

<div class="content">
    <div class="box box-danger">
        <div class="box-body">
            @Html.Raw(Constants.Messages.AccessDenied)
        </div>
    </div>
</div>

DuaControl.Web/Views/Shared/_DeleteDialog.cshtml
<div class="modal fade" id="deleteDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-sm btn-danger" id="btnYesDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

DuaControl.Web/Views/Shared/_Layout.cshtml
@using DuaControl.Web.Security
@using DuaControl.Web.Data

@inject IUserSession UserSession

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="~/logo.ico">
    <title>@ViewData["Title"] - Dua Control</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-datatables/css/dataTables.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/sb-admin-2.css" />
        @*<link rel="stylesheet" href="~/lib/jquery-datatables/css/datatables.css" />*@
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/dropzone.css" />
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/basic.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/alertify.min.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/themes/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-datatables/css/dataTables.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/sb-admin-2.css" />
        @*<link rel="stylesheet" href="~/lib/jquery-datatables/css/datatables.css" />*@
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/dropzone.css" />
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/basic.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/alertify.min.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/themes/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
</head>
<body id="page-top">
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Facturas" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-file-invoice"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Dua Control</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Facturas" asp-action="Index">
                    <i class="fas fa-fw fa-file-invoice-dollar"></i>
                    <span>Facturas</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Puertos" asp-action="Index">
                    <i class="fas fa-fw fa-anchor"></i>
                    <span>Puertos</span>
                </a>
            </li>
            @if (User.Identity.IsAuthenticated && UserSession.IsInRole(Constants.RoleNames.Administrator))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Index">
                        <i class="fas fa-fw fa-user-alt"></i>
                        <span>Usuarios</span>
                    </a>
                </li>
            }

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <li class="nav-item">
                <a class="nav-link" asp-controller="Account" asp-action="Logout">
                    <i class="fas fa-fw fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            </li>
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">@UserSession.FirstName @UserSession.LastName</span>

                                }
                                <img class="img-profile rounded-circle">
                            </a>

                            <!-- Dropdown - User Information -->
                            @*<div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal" asp-controller="Account" asp-action="Logout">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Logout
                                    </a>
                                </div>*@
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>&copy; 2020 - @DateTime.Now.Year - Dua Control by La Fabril C por A.</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
    </div>

    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Facturas" asp-action="Index">Dua Control</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Puertos" asp-action="Index">Puertos</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    @*<div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@
    @*<footer class="border-top footer text-muted">
            <div class="container">
                <p>&copy; 2020 - @DateTime.Now.Year - Dua Control by La Fabril C por A.</p>
            </div>
        </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/sb-admin-2.js"></script>
        <script src="~/lib/jquery-datatables/dist/datatables.js"></script>
        <script src="~/lib/jquery-datatables/dist/dataTables.bootstrap4.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/sb-admin-2.js"></script>
        <script src="~/lib/jquery-datatables/dist/datatables.js"></script>
        <script src="~/lib/jquery-datatables/dist/dataTables.bootstrap4.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DuaControl.Web/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DuaControl.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-datatables/css/dataTables.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="~/lib/jquery-datatables/css/datatables.css" />*@
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/dropzone.css" />
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/basic.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/alertify.min.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/themes/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/jquery-datatables/css/dataTables.bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="~/lib/jquery-datatables/css/datatables.css" />*@
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/dropzone.css" />
        <link rel="stylesheet" href="~/lib/dropzone/dist/css/basic.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/alertify.min.css" />
        <link rel="stylesheet" href="~/lib/alertifyjs/css/themes/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Facturas" asp-action="Index">Dua Control</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Puertos" asp-action="Index">Puertos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <partial name="_CookieConsentPartial" />

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <p>&copy; 2020 - @DateTime.Now.Year - Dua Control by La Fabril C por A.</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-datatables/dist/datatables.js"></script>
        <script src="~/lib/jquery-datatables/dist/dataTables.bootstrap4.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-datatables/dist/datatables.js"></script>
        <script src="~/lib/jquery-datatables/dist/dataTables.bootstrap4.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>